import assets from '../../02_Assets/assets.json' with { type: 'json' };
import profiles from '../../02_Assets/model-profiles.json' with { type: 'json' };
import { createRegistry } from '../../src/domain/registry.js';
import { planFilm } from '../../src/domain/planner.js';
import { compileShot } from '../../src/domain/compiler.js';

const registry=createRegistry(assets,profiles,{references:[]});
const allowed=new Set(['theme','projectId','assetManifestVersion','mode','requestedShots','rhythm','profileId']);
const json=(body,status=200,headers={})=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
function cors(request,env){const origin=request.headers.get('origin');const expected=env.ALLOWED_ORIGIN;return origin&&expected&&origin===expected?{'access-control-allow-origin':origin,'vary':'Origin'}:{};}
function auth(request,env){if(env.ENVIRONMENT!=='production'&&env.AUTH_MODE==='disabled')return{ok:true,clientId:'development'};if(env.AUTH_MODE==='access'&&request.headers.get('cf-access-authenticated-user-email'))return{ok:true,clientId:request.headers.get('cf-access-authenticated-user-email')};return{ok:false};}
export async function onRequest({request,env}){const headers=cors(request,env);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{...headers,'access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'content-type'}});const url=new URL(request.url);if(request.method==='GET'&&url.pathname.endsWith('/health'))return json({ready:true,requestId:crypto.randomUUID()},200,headers);if(request.method!=='POST')return json({error:'METHOD_NOT_ALLOWED',requestId:crypto.randomUUID()},405,headers);const identity=auth(request,env);if(!identity.ok)return json({error:'AUTH_REQUIRED',requestId:crypto.randomUUID()},401,headers);let body;try{body=await request.json()}catch{return json({error:'INVALID_JSON',requestId:crypto.randomUUID()},400,headers)}if(!body||Object.keys(body).some(key=>!allowed.has(key)))return json({error:'UNSUPPORTED_REQUEST_FIELD',requestId:crypto.randomUUID()},400,headers);if(typeof body.theme!=='string'||!body.theme.trim())return json({error:'MISSING_THEME',requestId:crypto.randomUUID()},400,headers);const profileId=body.profileId||'veo-3.1-lite';try{const {intent,plan,warnings}=planFilm({theme:body.theme,requestedShots:body.requestedShots||1,profileId},registry);const result=plan.shots.map(shot=>({...shot,...compileShot(shot,registry,registry.profileById.get(profileId))}));return json({ok:true,requestId:crypto.randomUUID(),intent,warnings,profileId,shots:result},200,headers)}catch{return json({error:'PLANNING_FAILED',requestId:crypto.randomUUID()},422,headers)}}
